version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_sports_app
    container_name: laravel_app
    restart: unless-stopped
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:vHzZlLKj4x9Q48R7bqbmWwXBiCjQSL9FeeZqyE5AkgM=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=sports_db
      - DB_USERNAME=root
      - DB_PASSWORD=root_password
    ports:
      - "8000:80"
    depends_on:
      - db
    volumes:
      - .:/var/www
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sports_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

  node:
    container_name: node
    image: node:lts
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 5173:5173

networks:
  laravel_network:

volumes:
  mysql_data:
